### ISSUE TITLE
revamp tnbfaucet.com

### ISSUE THREAD

**Issue by hussu010** [TNBFAUCET/TNBFAUCET#3]
Features:
- [x] Add and show recent faucet payments on the homepage.
- [x] Staff will add a Twitter post address and the site will identify if the post is eligible for the reward.
- [x] Payment can be made through the web app so no need to go to the account manager and make payment - Keysign

**Comment by hussu010** [comment]
Feat: Recent Faucet Payments, Statistics in the static HTML file

https://user-images.githubusercontent.com/55182298/118160002-74c4ee80-b43d-11eb-80d2-7060963c9043.mp4

**Comment by mrbusysky** [comment]
I have moved the files into a dev branch
